stages:
  - test
  - deploy

spec-test:
  tags:
    - puppet
  script:
    - "rake spec SPEC_OPTS='--format documentation'"
  stage: test

metadata-lint-test:
  tags:
    - puppet
  script:
    - "rake metadata_lint"
  stage: test

validate-test:
  tags:
    - puppet
  script:
    - "rake validate"
  stage: test

puppet-lint-test:
  tags:
    - puppet
  script:
    - "rake lint"
  stage: test

rubocop-test:
  tags:
    - puppet
  script:
    - "rake rubocop"
  stage: test

deploy:
  tags:
    - puppet
  script:
    - "/usr/local/bin/deploy.sh module newsyslog"
  stage: deploy
  only:
    - master

publish:
  tags:
    - puppet
  script:
    - rake module:clean
    - rake module:push
  stage: deploy
  only:
    - tags
